Use approved git plumbing to locate git directory, instead of just .git/xxx.

diff --git a/debian/git-hg b/debian/git-hg
--- a/debian/git-hg
+++ b/debian/git-hg
@@ -36,6 +36,14 @@ function canonicalize {
     printf "%s/%s\n" "$cdir" "$file"
 }
 
+function get-gitdir {
+    if [ -n "${GIT_DIR}" ]; then
+	echo "error: environment variable GIT_DIR must not be set"
+	exit 1
+    fi
+    GITDIR="$(git rev-parse --git-dir)"
+}
+
 function git-current-branch {
     git branch | egrep '^[*]' | sed 's/^\* \(.\)/\1/'
 }
@@ -81,18 +89,19 @@ function git-hg-clone {
     git init $CHECKOUT
     (
 	cd $CHECKOUT
-	hg clone -U $HG_REMOTE .git/hgcheckout
-	git init --bare .git/hgremote
+	get-gitdir
+	hg clone -U $HG_REMOTE ${GITDIR}/hgcheckout
+	git init --bare ${GITDIR}/hgremote
 	(
-	    cd .git/hgremote
+	    cd ${GITDIR}/hgremote
 	    $HG_FAST_EXPORT -r ../hgcheckout $FORCE
 	)
-	git remote add hg .git/hgremote
+	git remote add hg ${GITDIR}/hgremote
 	git fetch hg
         if git branch -r | grep -q master; then
 	    local branch="master"
         else
-            local branch=$(cd .git/hgcheckout/ && hg tip | grep branch | awk '{print $2}')
+            local branch=$(cd ${GITDIR}/hgcheckout/ && hg tip | grep branch | awk '{print $2}')
         fi
         git config hg.tracking.master $branch
         git pull hg $branch
@@ -105,9 +114,10 @@ function git-hg-fetch {
         FORCE="--force"
         shift
     fi
-    hg -R .git/hgcheckout pull
+    get-gitdir
+    hg -R ${GITDIR}/hgcheckout pull
     (
-	cd .git/hgremote
+	cd ${GITDIR}/hgremote
 	$HG_FAST_EXPORT $FORCE
     )
     git fetch hg
@@ -171,8 +181,9 @@ function git-hg-checkout {
 
 function git-hg-push {
     HG_REPO=$1
-    hg convert . .git/hgcheckout
-    hg -R .git/hgcheckout push $HG_REPO
+    get-gitdir
+    hg convert . ${GITDIR}/hgcheckout
+    hg -R ${GITDIR}/hgcheckout push $HG_REPO
 }
 
 function usage {
